[package]
name = "line-clipping"
description = "A simple crate implementing line clipping algorithms."
authors = ["Josh McKinney"]
license = "MIT OR Apache-2.0"
version = "0.3.1"
edition = "2021"
documentation = "https://docs.rs/line-clipping"
repository = "https://github.com/joshka/line-clipping"
readme = "README.md"
keywords = ["line", "clipping", "algorithm"]
categories = ["algorithms", "graphics"]

[dependencies]
bitflags = "2.9.0"

[dev-dependencies]
rstest = "0.25.0"

[lints.clippy]
nursery = { level = "warn" }
pedantic = { level = "warn" }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
